import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "pt" | "el" | "he" | "la" | "fr";

export const LANGUAGES: { code: Lang; label: string; nativeLabel: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English",    nativeLabel: "EN", dir: "ltr" },
  { code: "pt", label: "Português",  nativeLabel: "PT", dir: "ltr" },
  { code: "el", label: "Ελληνικά",   nativeLabel: "EL", dir: "ltr" },
  { code: "he", label: "עברית",       nativeLabel: "HE", dir: "rtl" },
  { code: "la", label: "Latīna",     nativeLabel: "LA", dir: "ltr" },
  { code: "fr", label: "Français",   nativeLabel: "FR", dir: "ltr" },
];

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.about": "About", "nav.glossary": "Glossary", "nav.contact": "Get in Touch",
    "hero.tagline": "Gramma Institute", "hero.headline1": "Read the Text.", "hero.headline2": "Not the Translation.",
    "hero.subtitle": "Biblical Greek, Biblical Hebrew, Latin, English, Portuguese, and Descriptive Linguistics — taught with the rigor they deserve, for those who will not settle for secondhand knowledge.",
    "hero.explore": "EXPLORE COURSES", "hero.touch": "GET IN TOUCH", "hero.scroll": "SCROLL",
    "courses.label": "Our Languages", "courses.title1": "Six Languages.", "courses.title2": "One Purpose.",
    "courses.body": "The canon of Western civilisation — theological, philosophical, and literary — was written in these languages. Access it directly.",
    "courses.learn": "Learn More",
    "why.label": "The Case for Primary Sources", "why.title": "Why the Original Language",
    "why.1.title": "Precision Beyond Translation", "why.1.body": "Every translation is an interpretation. Translators make thousands of choices — in vocabulary, syntax, and nuance — that you never see. Original languages eliminate that layer entirely.",
    "why.2.title": "Access to the Author's Intent", "why.2.body": "Words carry weight specific to their era. The Greek of Paul, the Hebrew of Moses, the Latin of Augustine — each carries meaning that no English word can fully capture. Read them yourself.",
    "why.3.title": "Intellectual Discipline", "why.3.body": "Learning ancient languages reshapes how you think. The grammar demands precision. The vocabulary demands attention. The result is a mind trained for exactness — in all things, not just language.",
    "why.4.title": "A Living Tradition", "why.4.body": "You join a chain of scholars stretching across centuries — monks, reformers, theologians — who believed these languages were worth the effort. That chain has never broken for good reason.",
    "why.quote": '"The original text is the only text."',
    "cta.label": "Begin Your Study", "cta.title1": "The Text Has Been Waiting.", "cta.title2": "Are You Ready?",
    "cta.body": "Contact us for more information about our courses, schedules, and enrollment. We answer every inquiry personally.",
    "cta.button": "GET IN TOUCH",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "About the", "about.hero.title2": "Institute",
    "about.mission.label": "Our Mission", "about.mission.text": "To equip serious students with direct, unmediated access to the texts that have shaped Western civilisation and Christian thought — by teaching the languages in which those texts were written.",
    "about.mission.p1": "Gramma Institute was founded on a single conviction: that the most important texts in history deserve to be read in their original languages. Translation is interpretation. And interpretation, however faithful, always introduces distance between the reader and the text.",
    "about.mission.p2": "We close that distance. Through rigorous instruction in Biblical Greek, Biblical Hebrew, Latin, English, Portuguese, and Descriptive Linguistics, we give students the tools to engage the primary sources directly — with precision, depth, and intellectual independence.",
    "about.mission.p3": "Our students are pastors, theologians, seminarians, academics, and independent scholars who are not satisfied with secondhand knowledge. They want to read the text. We teach them to do exactly that.",
    "about.mission.p4": "The languages we teach are not merely academic subjects. They are living windows into the Word of God and the intellectual heritage of the Church. We approach them with the seriousness they deserve.",
    "about.pillars.label": "Our Principles", "about.pillars.title": "What We Stand For",
    "about.pillars.1.title": "Rigor Without Compromise", "about.pillars.1.body": "We do not teach simplified grammars or shortcut methods. We teach the languages as they were written — with full morphology, syntax, and philological precision. Shortcuts produce readers who cannot read.",
    "about.pillars.2.title": "Text-Centred Learning", "about.pillars.2.body": "Every lesson drives toward the primary text. Grammar and vocabulary are tools. The goal is always the same: to open the text and read it yourself, without intermediaries.",
    "about.pillars.3.title": "Theological Seriousness", "about.pillars.3.body": "These are not merely classical languages. They are the languages of Scripture and of two millennia of Christian thought. We approach them with the gravity that demands.",
    "about.pillars.4.title": "Scholarly Tradition", "about.pillars.4.body": "Our methods stand in a tradition of language instruction stretching from the Reformation grammarians to the great universities of Europe. We are heirs to that tradition and we honour it.",
    "about.cta.label": "Begin", "about.cta.title": "Ready to Read the Text?", "about.cta.body": "Choose your language and begin. Every great scholar started where you are now.",
    "about.cta.courses": "View Courses", "about.cta.touch": "Get in Touch",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "Key Terms in", "glossary.hero.title2": "Three Languages",
    "glossary.hero.subtitle": "A curated glossary of theologically and philologically significant terms — with their original script, transliteration, and scholarly notes.",
    "glossary.tab.all": "All Languages", "glossary.tab.greek": "Greek", "glossary.tab.hebrew": "Hebrew", "glossary.tab.latin": "Latin",
    "glossary.search": "Search terms...", "glossary.empty": "No terms found for",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "Get in", "contact.hero.title2": "Touch",
    "contact.hero.subtitle": "Whether you are enquiring about a course, considering enrolment, or have a question about our work — we welcome your message.",
    "contact.info.label": "Correspondence", "contact.info.body": "We respond to all enquiries within two to three business days. For urgent matters, please note the nature of your request in the subject line.",
    "contact.email.label": "Email", "contact.response.label": "Response Time", "contact.response.value": "2–3 business days",
    "contact.courses.label": "Courses", "contact.form.name": "Full Name *", "contact.form.email": "Email Address *",
    "contact.form.type": "Nature of Enquiry", "contact.form.message": "Message *", "contact.form.send": "Send Message", "contact.form.sending": "Sending...",
    "contact.form.name.ph": "Your name", "contact.form.email.ph": "your@email.com", "contact.form.message.ph": "Your message...",
    "contact.success.title": "Message Received", "contact.success.body": "Thank you, {name}. We will be in touch within two to three business days.",
    "contact.enquiry.course": "Course Enquiry", "contact.enquiry.enrol": "Enrolment", "contact.enquiry.partner": "Institutional Partnership",
    "contact.enquiry.media": "Media / Press", "contact.enquiry.other": "Other",
    "footer.copy": "© 2025 Gramma Institute", "whatsapp.label": "WhatsApp",
  },
  pt: {
    "nav.home": "Início", "nav.about": "Sobre", "nav.glossary": "Glossário", "nav.contact": "Entre em Contato",
    "hero.tagline": "Gramma Institute", "hero.headline1": "Leia o Texto.", "hero.headline2": "Não a Tradução.",
    "hero.subtitle": "Grego Bíblico, Hebraico Bíblico, Latim, Inglês, Português e Linguística Descritiva — ensinados com o rigor que merecem, para quem não se contenta com conhecimento de segunda mão.",
    "hero.explore": "EXPLORAR CURSOS", "hero.touch": "ENTRAR EM CONTATO", "hero.scroll": "ROLAR",
    "courses.label": "Nossos Idiomas", "courses.title1": "Seis Idiomas.", "courses.title2": "Um Propósito.",
    "courses.body": "O cânone da civilização ocidental — teológico, filosófico e literário — foi escrito nessas línguas. Acesse-o diretamente.",
    "courses.learn": "Saiba Mais",
    "why.label": "O Argumento pelas Fontes Primárias", "why.title": "Por Que o Idioma Original",
    "why.1.title": "Precisão Além da Tradução", "why.1.body": "Toda tradução é uma interpretação. Os tradutores fazem milhares de escolhas — em vocabulário, sintaxe e nuance — que você nunca vê. Os idiomas originais eliminam completamente essa camada.",
    "why.2.title": "Acesso à Intenção do Autor", "why.2.body": "As palavras carregam peso específico de sua época. O grego de Paulo, o hebraico de Moisés, o latim de Agostinho — cada um carrega significados que nenhuma palavra portuguesa pode capturar completamente.",
    "why.3.title": "Disciplina Intelectual", "why.3.body": "Aprender idiomas antigos reformula sua maneira de pensar. A gramática exige precisão. O vocabulário exige atenção. O resultado é uma mente treinada para a exatidão.",
    "why.4.title": "Uma Tradição Viva", "why.4.body": "Você se junta a uma cadeia de estudiosos que se estende por séculos — monges, reformadores, teólogos — que acreditavam que esses idiomas valiam o esforço.",
    "why.quote": '"O texto original é o único texto."',
    "cta.label": "Comece Seu Estudo", "cta.title1": "O Texto Tem Esperado.", "cta.title2": "Você Está Pronto?",
    "cta.body": "Entre em contato para mais informações sobre nossos cursos, horários e matrículas. Respondemos a todas as consultas pessoalmente.",
    "cta.button": "ENTRAR EM CONTATO",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "Sobre o", "about.hero.title2": "Instituto",
    "about.mission.label": "Nossa Missão", "about.mission.text": "Equipar estudantes sérios com acesso direto e imediato aos textos que moldaram a civilização ocidental e o pensamento cristão — ensinando os idiomas nos quais esses textos foram escritos.",
    "about.mission.p1": "O Gramma Institute foi fundado em uma única convicção: que os textos mais importantes da história merecem ser lidos em seus idiomas originais. A tradução é interpretação. E a interpretação, por mais fiel que seja, sempre introduz distância entre o leitor e o texto.",
    "about.mission.p2": "Nós fechamos essa distância. Por meio de instrução rigorosa em Grego Bíblico, Hebraico Bíblico, Latim, Inglês, Português e Linguística Descritiva.",
    "about.mission.p3": "Nossos alunos são pastores, teólogos, seminaristas, acadêmicos e estudiosos independentes que não se satisfazem com conhecimento de segunda mão.",
    "about.mission.p4": "Os idiomas que ensinamos não são meramente matérias acadêmicas. São janelas vivas para a Palavra de Deus e a herança intelectual da Igreja.",
    "about.pillars.label": "Nossos Princípios", "about.pillars.title": "No Que Acreditamos",
    "about.pillars.1.title": "Rigor Sem Concessões", "about.pillars.1.body": "Não ensinamos gramáticas simplificadas ou métodos de atalho. Ensinamos os idiomas como foram escritos — com morfologia, sintaxe e precisão filológica completas.",
    "about.pillars.2.title": "Aprendizado Centrado no Texto", "about.pillars.2.body": "Cada lição avança em direção ao texto primário. Gramática e vocabulário são ferramentas. O objetivo é sempre o mesmo: abrir o texto e lê-lo você mesmo.",
    "about.pillars.3.title": "Seriedade Teológica", "about.pillars.3.body": "Estes não são meramente idiomas clássicos. São as línguas da Escritura e de dois milênios de pensamento cristão.",
    "about.pillars.4.title": "Tradição Acadêmica", "about.pillars.4.body": "Nossos métodos estão numa tradição de ensino de idiomas que vai dos gramáticos da Reforma às grandes universidades europeias.",
    "about.cta.label": "Comece", "about.cta.title": "Pronto para Ler o Texto?", "about.cta.body": "Escolha seu idioma e comece. Todo grande estudioso começou onde você está agora.",
    "about.cta.courses": "Ver Cursos", "about.cta.touch": "Entre em Contato",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "Termos-Chave em", "glossary.hero.title2": "Três Idiomas",
    "glossary.hero.subtitle": "Um glossário curado de termos teológica e filologicamente significativos — com o texto original, transliteração e notas acadêmicas.",
    "glossary.tab.all": "Todos os Idiomas", "glossary.tab.greek": "Grego", "glossary.tab.hebrew": "Hebraico", "glossary.tab.latin": "Latim",
    "glossary.search": "Pesquisar termos...", "glossary.empty": "Nenhum termo encontrado para",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "Entre em", "contact.hero.title2": "Contato",
    "contact.hero.subtitle": "Se você está a perguntar sobre um curso, a considerar a matrícula ou tem uma dúvida — bem-vindo à sua mensagem.",
    "contact.info.label": "Correspondência", "contact.info.body": "Respondemos a todas as consultas dentro de dois a três dias úteis.",
    "contact.email.label": "E-mail", "contact.response.label": "Tempo de Resposta", "contact.response.value": "2–3 dias úteis",
    "contact.courses.label": "Cursos", "contact.form.name": "Nome Completo *", "contact.form.email": "Endereço de E-mail *",
    "contact.form.type": "Natureza da Consulta", "contact.form.message": "Mensagem *", "contact.form.send": "Enviar Mensagem", "contact.form.sending": "Enviando...",
    "contact.form.name.ph": "Seu nome", "contact.form.email.ph": "seu@email.com", "contact.form.message.ph": "Sua mensagem...",
    "contact.success.title": "Mensagem Recebida", "contact.success.body": "Obrigado, {name}. Entraremos em contato dentro de dois a três dias úteis.",
    "contact.enquiry.course": "Consulta sobre Curso", "contact.enquiry.enrol": "Matrícula", "contact.enquiry.partner": "Parceria Institucional",
    "contact.enquiry.media": "Mídia / Imprensa", "contact.enquiry.other": "Outro",
    "footer.copy": "© 2025 Gramma Institute", "whatsapp.label": "WhatsApp",
  },
  el: {
    "nav.home": "Αρχική", "nav.about": "Σχετικά", "nav.glossary": "Γλωσσάρι", "nav.contact": "Επικοινωνία",
    "hero.tagline": "Gramma Institute", "hero.headline1": "Διαβάστε το Κείμενο.", "hero.headline2": "Όχι τη Μετάφραση.",
    "hero.subtitle": "Βιβλική Ελληνική, Βιβλική Εβραϊκή, Λατινικά, Αγγλικά, Πορτογαλικά και Περιγραφική Γλωσσολογία — διδασκόμενα με την αυστηρότητα που αξίζουν, για εκείνους που δεν αρκούνται σε γνώση εξ δευτέρας χειρός.",
    "hero.explore": "ΕΞΕΡΕΥΝΗΣΗ ΜΑΘΗΜΑΤΩΝ", "hero.touch": "ΕΠΙΚΟΙΝΩΝΗΣΤΕ", "hero.scroll": "ΚΥΛΙΣΤΕ",
    "courses.label": "Οι Γλώσσες Μας", "courses.title1": "Έξι Γλώσσες.", "courses.title2": "Ένας Σκοπός.",
    "courses.body": "Ο κανόνας του δυτικού πολιτισμού — θεολογικός, φιλοσοφικός και λογοτεχνικός — γράφτηκε σε αυτές τις γλώσσες. Αποκτήστε απευθείας πρόσβαση.",
    "courses.learn": "Μάθετε Περισσότερα",
    "why.label": "Η Υπόθεση για Πρωτογενείς Πηγές", "why.title": "Γιατί η Πρωτότυπη Γλώσσα",
    "why.1.title": "Ακρίβεια Πέρα από τη Μετάφραση", "why.1.body": "Κάθε μετάφραση είναι ερμηνεία. Οι μεταφραστές κάνουν χιλιάδες επιλογές — στο λεξιλόγιο, τη σύνταξη και τις αποχρώσεις — που δεν βλέπετε ποτέ. Οι πρωτότυπες γλώσσες εξαλείφουν εντελώς αυτό το επίπεδο.",
    "why.2.title": "Πρόσβαση στην Πρόθεση του Συγγραφέα", "why.2.body": "Οι λέξεις φέρουν βάρος ειδικό για την εποχή τους. Τα ελληνικά του Παύλου, τα εβραϊκά του Μωυσή, τα λατινικά του Αυγουστίνου — το καθένα φέρει νόημα που καμία άλλη γλώσσα δεν μπορεί να αποδώσει πλήρως.",
    "why.3.title": "Πνευματική Πειθαρχία", "why.3.body": "Η εκμάθηση αρχαίων γλωσσών αναδιαμορφώνει τον τρόπο σκέψης σας. Η γραμματική απαιτεί ακρίβεια. Το λεξιλόγιο απαιτεί προσοχή. Το αποτέλεσμα είναι ένα μυαλό εκπαιδευμένο για ακρίβεια.",
    "why.4.title": "Μια Ζωντανή Παράδοση", "why.4.body": "Ενώνεστε με μια αλυσίδα μελετητών που εκτείνεται σε αιώνες — μοναχοί, μεταρρυθμιστές, θεολόγοι — που πίστευαν ότι αυτές οι γλώσσες άξιζαν την προσπάθεια.",
    "why.quote": '"Το πρωτότυπο κείμενο είναι το μόνο κείμενο."',
    "cta.label": "Ξεκινήστε τη Μελέτη Σας", "cta.title1": "Το Κείμενο Σας Περιμένει.", "cta.title2": "Είστε Έτοιμοι;",
    "cta.body": "Επικοινωνήστε μαζί μας για περισσότερες πληροφορίες σχετικά με τα μαθήματα, τα προγράμματα και την εγγραφή. Απαντάμε σε κάθε ερώτηση προσωπικά.",
    "cta.button": "ΕΠΙΚΟΙΝΩΝΗΣΤΕ ΜΑΖΙ ΜΑΣ",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "Σχετικά με το", "about.hero.title2": "Ινστιτούτο",
    "about.mission.label": "Η Αποστολή Μας", "about.mission.text": "Να εξοπλίσουμε σοβαρούς φοιτητές με άμεση, αδιαμεσολάβητη πρόσβαση στα κείμενα που διαμόρφωσαν τον δυτικό πολιτισμό και τη χριστιανική σκέψη.",
    "about.mission.p1": "Το Gramma Institute ιδρύθηκε με μια μοναδική πεποίθηση: ότι τα πιο σημαντικά κείμενα στην ιστορία αξίζει να διαβαστούν στις πρωτότυπες γλώσσες τους. Η μετάφραση είναι ερμηνεία. Και η ερμηνεία, όσο πιστή κι αν είναι, πάντα εισάγει απόσταση μεταξύ του αναγνώστη και του κειμένου.",
    "about.mission.p2": "Κλείνουμε αυτή την απόσταση. Μέσω αυστηρής διδασκαλίας σε Βιβλική Ελληνική, Βιβλική Εβραϊκή, Λατινικά, Αγγλικά, Πορτογαλικά και Περιγραφική Γλωσσολογία.",
    "about.mission.p3": "Οι φοιτητές μας είναι ποιμένες, θεολόγοι, σπουδαστές σεμιναρίου, ακαδημαϊκοί και ανεξάρτητοι μελετητές που δεν αρκούνται σε γνώση εξ δευτέρας χειρός.",
    "about.mission.p4": "Οι γλώσσες που διδάσκουμε δεν είναι απλώς ακαδημαϊκά αντικείμενα. Είναι ζωντανά παράθυρα στον Λόγο του Θεού και στην πνευματική κληρονομιά της Εκκλησίας.",
    "about.pillars.label": "Οι Αρχές Μας", "about.pillars.title": "Τι Υποστηρίζουμε",
    "about.pillars.1.title": "Αυστηρότητα Χωρίς Συμβιβασμό", "about.pillars.1.body": "Δεν διδάσκουμε απλοποιημένες γραμματικές ή μεθόδους συντομεύσεων. Διδάσκουμε τις γλώσσες όπως γράφτηκαν — με πλήρη μορφολογία, σύνταξη και φιλολογική ακρίβεια.",
    "about.pillars.2.title": "Μάθηση Επικεντρωμένη στο Κείμενο", "about.pillars.2.body": "Κάθε μάθημα οδηγεί προς το πρωτογενές κείμενο. Η γραμματική και το λεξιλόγιο είναι εργαλεία. Ο στόχος είναι πάντα ο ίδιος: να ανοίξετε το κείμενο και να το διαβάσετε μόνοι σας.",
    "about.pillars.3.title": "Θεολογική Σοβαρότητα", "about.pillars.3.body": "Αυτές δεν είναι απλώς κλασικές γλώσσες. Είναι οι γλώσσες της Γραφής και δύο χιλιετιών χριστιανικής σκέψης.",
    "about.pillars.4.title": "Ακαδημαϊκή Παράδοση", "about.pillars.4.body": "Οι μέθοδοί μας βρίσκονται σε μια παράδοση διδασκαλίας γλωσσών από τους γραμματικούς της Μεταρρύθμισης έως τα μεγάλα πανεπιστήμια της Ευρώπης.",
    "about.cta.label": "Ξεκινήστε", "about.cta.title": "Έτοιμοι να Διαβάσετε το Κείμενο;", "about.cta.body": "Επιλέξτε τη γλώσσα σας και ξεκινήστε. Κάθε μεγάλος μελετητής ξεκίνησε από εκεί που βρίσκεστε τώρα.",
    "about.cta.courses": "Δείτε τα Μαθήματα", "about.cta.touch": "Επικοινωνήστε",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "Βασικοί Όροι σε", "glossary.hero.title2": "Τρεις Γλώσσες",
    "glossary.hero.subtitle": "Ένα επιλεγμένο γλωσσάρι θεολογικά και φιλολογικά σημαντικών όρων — με το αρχικό κείμενο, μεταγραφή και ακαδημαϊκές σημειώσεις.",
    "glossary.tab.all": "Όλες οι Γλώσσες", "glossary.tab.greek": "Ελληνικά", "glossary.tab.hebrew": "Εβραϊκά", "glossary.tab.latin": "Λατινικά",
    "glossary.search": "Αναζήτηση όρων...", "glossary.empty": "Δεν βρέθηκαν όροι για",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "Επικοινωνήστε", "contact.hero.title2": "Μαζί Μας",
    "contact.hero.subtitle": "Είτε ρωτάτε για ένα μάθημα, σκέφτεστε την εγγραφή ή έχετε μια ερώτηση — καλωσορίζουμε το μήνυμά σας.",
    "contact.info.label": "Αλληλογραφία", "contact.info.body": "Απαντάμε σε όλες τις ερωτήσεις εντός δύο έως τριών εργάσιμων ημερών.",
    "contact.email.label": "Email", "contact.response.label": "Χρόνος Απόκρισης", "contact.response.value": "2–3 εργάσιμες ημέρες",
    "contact.courses.label": "Μαθήματα", "contact.form.name": "Ονοματεπώνυμο *", "contact.form.email": "Διεύθυνση Email *",
    "contact.form.type": "Φύση Ερωτήματος", "contact.form.message": "Μήνυμα *", "contact.form.send": "Αποστολή Μηνύματος", "contact.form.sending": "Αποστολή...",
    "contact.form.name.ph": "Το όνομά σας", "contact.form.email.ph": "your@email.com", "contact.form.message.ph": "Το μήνυμά σας...",
    "contact.success.title": "Μήνυμα Ελήφθη", "contact.success.body": "Ευχαριστούμε, {name}. Θα επικοινωνήσουμε μαζί σας εντός δύο έως τριών εργάσιμων ημερών.",
    "contact.enquiry.course": "Ερώτηση για Μάθημα", "contact.enquiry.enrol": "Εγγραφή", "contact.enquiry.partner": "Θεσμική Συνεργασία",
    "contact.enquiry.media": "Μέσα / Τύπος", "contact.enquiry.other": "Άλλο",
    "footer.copy": "© 2025 Gramma Institute", "whatsapp.label": "WhatsApp",
  },
  he: {
    "nav.home": "בית", "nav.about": "אודות", "nav.glossary": "מונחון", "nav.contact": "צור קשר",
    "hero.tagline": "Gramma Institute", "hero.headline1": "קרא את הטקסט.", "hero.headline2": "לא את התרגום.",
    "hero.subtitle": "יוונית מקראית, עברית מקראית, לטינית, אנגלית, פורטוגזית ובלשנות תיאורית — מלמדות בקפדנות הראויה להן, למי שאינו מסתפק בידע מזוהמים.",
    "hero.explore": "גלה קורסים", "hero.touch": "צור קשר", "hero.scroll": "גלול",
    "courses.label": "השפות שלנו", "courses.title1": "שש שפות.", "courses.title2": "מטרה אחת.",
    "courses.body": "הקאנון של הציוויליזציה המערבית — תיאולוגי, פילוסופי וספרותי — נכתב בשפות אלו. גש אליו ישירות.",
    "courses.learn": "למד עוד",
    "why.label": "הטיעון למקורות ראשוניים", "why.title": "מדוע השפה המקורית",
    "why.1.title": "דיוק מעבר לתרגום", "why.1.body": "כל תרגום הוא פרשנות. המתרגמים עושים אלפי בחירות — במילים, בתחביר ובניואנסים — שאתה לעולם לא רואה. השפות המקוריות מסלקות לחלוטין את השכבה הזו.",
    "why.2.title": "גישה לכוונת המחבר", "why.2.body": "מילים נושאות משקל ספציפי לתקופתן. היוונית של פאולוס, העברית של משה, הלטינית של אוגוסטינוס — כל אחת נושאת משמעות שאף מילה אחרת אינה יכולה ללכוד.",
    "why.3.title": "משמעת אינטלקטואלית", "why.3.body": "לימוד שפות עתיקות מעצב מחדש את אופן חשיבתך. הדקדוק דורש דיוק. האוצר מילים דורש קשב. התוצאה היא מוח מאומן לדייקנות.",
    "why.4.title": "מסורת חיה", "why.4.body": "אתה מצטרף לשרשרת של חוקרים המשתרעת על פני מאות שנים — נזירים, מתקנים, תיאולוגים — שהאמינו ששפות אלו שוות את המאמץ.",
    "why.quote": '"הטקסט המקורי הוא הטקסט היחיד."',
    "cta.label": "התחל את הלימוד שלך", "cta.title1": "הטקסט מחכה.", "cta.title2": "האם אתה מוכן?",
    "cta.body": "צור קשר למידע נוסף על הקורסים, לוחות הזמנים וההרשמה. אנו עונים על כל פנייה באופן אישי.",
    "cta.button": "צור קשר",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "אודות", "about.hero.title2": "המכון",
    "about.mission.label": "המשימה שלנו", "about.mission.text": "לצייד תלמידים רציניים בגישה ישירה וללא תיווך לטקסטים שעיצבו את הציוויליזציה המערבית והמחשבה הנוצרית.",
    "about.mission.p1": "Gramma Institute נוסד על סמך אמונה אחת: שהטקסטים החשובים ביותר בהיסטוריה ראויים להיקרא בשפות המקוריות שלהם. תרגום הוא פרשנות. ופרשנות, כמה שהיא אמינה, תמיד מכניסה מרחק בין הקורא לטקסט.",
    "about.mission.p2": "אנו סוגרים את הפער הזה. באמצעות הוראה קפדנית ביוונית מקראית, עברית מקראית, לטינית, אנגלית, פורטוגזית ובלשנות תיאורית.",
    "about.mission.p3": "התלמידים שלנו הם רועי עדר, תיאולוגים, סמינריסטים, אקדמאים וחוקרים עצמאיים שאינם מסתפקים בידע מזוהמים.",
    "about.mission.p4": "השפות שאנו מלמדים אינן רק נושאים אקדמיים. הן חלונות חיים לדבר האלוהים ולמורשת האינטלקטואלית של הכנסייה.",
    "about.pillars.label": "העקרונות שלנו", "about.pillars.title": "מה אנחנו עומדים עליו",
    "about.pillars.1.title": "קפדנות ללא פשרות", "about.pillars.1.body": "אנחנו לא מלמדים דקדוקים מפושטים או שיטות קיצור. אנחנו מלמדים את השפות כפי שנכתבו — עם מורפולוגיה, תחביר ודיוק פילולוגי מלא.",
    "about.pillars.2.title": "למידה ממוקדת טקסט", "about.pillars.2.body": "כל שיעור מוביל לטקסט הראשוני. דקדוק ואוצר מילים הם כלים. המטרה תמיד זהה: לפתוח את הטקסט ולקרוא אותו בעצמך, ללא מתווכים.",
    "about.pillars.3.title": "רצינות תיאולוגית", "about.pillars.3.body": "אלו אינן רק שפות קלאסיות. הן שפות הכתוב ושל אלפיים שנות מחשבה נוצרית.",
    "about.pillars.4.title": "מסורת מלומדת", "about.pillars.4.body": "שיטותינו עומדות במסורת של הוראת שפות המשתרעת מדקדוקי הרפורמציה אל האוניברסיטאות הגדולות של אירופה.",
    "about.cta.label": "התחל", "about.cta.title": "מוכן לקרוא את הטקסט?", "about.cta.body": "בחר את השפה שלך והתחל. כל מלומד גדול התחיל היכן שאתה נמצא עכשיו.",
    "about.cta.courses": "צפה בקורסים", "about.cta.touch": "צור קשר",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "מונחי מפתח ב", "glossary.hero.title2": "שלוש שפות",
    "glossary.hero.subtitle": "מילון מונחים מאוצר של מונחים בעלי משמעות תיאולוגית ופילולוגית — עם הכתב המקורי, תעתיק והערות.",
    "glossary.tab.all": "כל השפות", "glossary.tab.greek": "יוונית", "glossary.tab.hebrew": "עברית", "glossary.tab.latin": "לטינית",
    "glossary.search": "חפש מונחים...", "glossary.empty": "לא נמצאו מונחים עבור",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "צור", "contact.hero.title2": "קשר",
    "contact.hero.subtitle": "בין אם אתה שואל על קורס, שוקל הרשמה, או יש לך שאלה — אנחנו מברכים על הודעתך.",
    "contact.info.label": "התכתבות", "contact.info.body": "אנו מגיבים לכל הפניות תוך שניים עד שלושה ימי עסקים.",
    "contact.email.label": "אימייל", "contact.response.label": "זמן תגובה", "contact.response.value": "2–3 ימי עסקים",
    "contact.courses.label": "קורסים", "contact.form.name": "שם מלא *", "contact.form.email": "כתובת אימייל *",
    "contact.form.type": "אופי הפנייה", "contact.form.message": "הודעה *", "contact.form.send": "שלח הודעה", "contact.form.sending": "שולח...",
    "contact.form.name.ph": "שמך", "contact.form.email.ph": "your@email.com", "contact.form.message.ph": "הודעתך...",
    "contact.success.title": "ההודעה התקבלה", "contact.success.body": "תודה, {name}. נצור אתך קשר תוך שניים עד שלושה ימי עסקים.",
    "contact.enquiry.course": "שאלה על קורס", "contact.enquiry.enrol": "הרשמה", "contact.enquiry.partner": "שותפות מוסדית",
    "contact.enquiry.media": "מדיה / עיתונות", "contact.enquiry.other": "אחר",
    "footer.copy": "© 2025 Gramma Institute", "whatsapp.label": "WhatsApp",
  },
  la: {
    "nav.home": "Principium", "nav.about": "De Nobis", "nav.glossary": "Glossarium", "nav.contact": "Colloquium",
    "hero.tagline": "Gramma Institute", "hero.headline1": "Lege Textum.", "hero.headline2": "Non Translationem.",
    "hero.subtitle": "Graecum Biblicum, Hebraeum Biblicum, Latina, Anglica, Lusitana et Linguistica Descriptiva — docta cum rigore quo digna sunt, pro eis qui scientia secunda manu contenti non sunt.",
    "hero.explore": "CURSUS EXPLORA", "hero.touch": "COLLOQUERE", "hero.scroll": "VOLVERE",
    "courses.label": "Linguae Nostrae", "courses.title1": "Sex Linguae.", "courses.title2": "Unum Propositum.",
    "courses.body": "Canon civilizationis occidentalis — theologicus, philosophicus, literarius — his in linguis scriptus est. Accede directe.",
    "courses.learn": "Plus Disce",
    "why.label": "Pro Fontibus Primariis", "why.title": "Cur Lingua Originalis",
    "why.1.title": "Accuratio Ultra Translationem", "why.1.body": "Omnis translatio interpretatio est. Interpretes millia electionum faciunt — in vocabulario, syntaxi, et subtilitate — quas numquam vides. Linguae originales hunc gradum omnino tollunt.",
    "why.2.title": "Ad Mentem Auctoris Accessus", "why.2.body": "Verba pondus habent suae aetati proprium. Graecum Pauli, Hebraeum Moysis, Latinum Augustini — quodque sensum portat quem nulla alia lingua plene capere potest.",
    "why.3.title": "Disciplina Intellectualis", "why.3.body": "Discere linguas antiquas mentem tuam mutat. Grammatica diligentiam postulat. Vocabularium attentionem postulat. Effectus est mens ad exactitudinem instituta.",
    "why.4.title": "Traditio Viva", "why.4.body": "Te iungis catenae eruditorum per saecula extentae — monachis, reformatoribus, theologis — qui has linguas labore dignas credebant.",
    "why.quote": '"Textus originalis solus textus est."',
    "cta.label": "Studium Incipe", "cta.title1": "Textus Te Exspectat.", "cta.title2": "Parasne?",
    "cta.body": "Nobiscum colloquere de cursu, temporibus, et inscriptione. Omnes interrogationes personaliter respondemus.",
    "cta.button": "COLLOQUERE",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "De", "about.hero.title2": "Instituto",
    "about.mission.label": "Propositum Nostrum", "about.mission.text": "Discipulos serios instruere accessu directo et immediato ad textus qui civilizationem occidentalem et mentem Christianam formaverunt.",
    "about.mission.p1": "Gramma Institute una persuasione fundatum est: textus maximi momenti historiae in linguis originalibus legi debere. Translatio interpretatio est. Et interpretatio, quamvis fidelis, semper distantiam inter lectorem et textum introducit.",
    "about.mission.p2": "Hanc distantiam claudimus. Per institutionem rigidam in Graeco Biblico, Hebraeo Biblico, Latina, Anglica, Lusitana et Linguistica Descriptiva.",
    "about.mission.p3": "Discipuli nostri sunt pastores, theologi, seminariorum alumni, academici et docti privati qui scientia secunda manu contenti non sunt.",
    "about.mission.p4": "Linguae quas docemus non tantum scholasticae materiae sunt. Fenestrae viventes in Verbum Dei et hereditatem intellectualem Ecclesiae sunt.",
    "about.pillars.label": "Principia Nostra", "about.pillars.title": "Pro Quibus Stamus",
    "about.pillars.1.title": "Rigor Sine Concessione", "about.pillars.1.body": "Non grammaticas simplificatas aut vias compendiosas docemus. Linguas ut scriptae sunt docemus — cum plena morphologia, syntaxi et accuratione philologica.",
    "about.pillars.2.title": "Eruditio Textu Centrata", "about.pillars.2.body": "Omnis lectio ad textum primarium tendit. Grammatica et vocabularium instrumenta sunt. Propositum semper idem est: textum aperire et ipse legere.",
    "about.pillars.3.title": "Serietas Theologica", "about.pillars.3.body": "Hae non tantum linguae classicae sunt. Linguae Scripturae et duorum millenariorum cogitationis Christianae sunt.",
    "about.pillars.4.title": "Traditio Scholastica", "about.pillars.4.body": "Methodi nostrae in traditione institutionis linguarum a grammaticis Reformationis ad magnas universitates Europae stant.",
    "about.cta.label": "Incipe", "about.cta.title": "Paratusne Textum Legere?", "about.cta.body": "Linguam tuam elige et incipe. Omnis magnus eruditus ubi tu nunc es incepit.",
    "about.cta.courses": "Cursus Vide", "about.cta.touch": "Colloquere",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "Termini Praecipui in", "glossary.hero.title2": "Tribus Linguis",
    "glossary.hero.subtitle": "Glossarium curatum terminorum theologice et philologice significantium — cum scriptura originali, transcriptione et notis eruditis.",
    "glossary.tab.all": "Omnes Linguae", "glossary.tab.greek": "Graeca", "glossary.tab.hebrew": "Hebraea", "glossary.tab.latin": "Latina",
    "glossary.search": "Terminos quaere...", "glossary.empty": "Nulli termini inventi pro",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "Colloquere", "contact.hero.title2": "Nobiscum",
    "contact.hero.subtitle": "Sive de cursu interrogas, sive inscriptionem consideras, sive quaestionem habes — epistulam tuam libenter accipimus.",
    "contact.info.label": "Correspondentia", "contact.info.body": "Omnibus interrogationibus intra duos ad tres dies negotii respondemus.",
    "contact.email.label": "Inscriptio Electronica", "contact.response.label": "Tempus Responsionis", "contact.response.value": "2–3 dies negotii",
    "contact.courses.label": "Cursus", "contact.form.name": "Nomen Plenum *", "contact.form.email": "Inscriptio Electronica *",
    "contact.form.type": "Genus Interrogationis", "contact.form.message": "Epistula *", "contact.form.send": "Epistulam Mitte", "contact.form.sending": "Mittens...",
    "contact.form.name.ph": "Nomen tuum", "contact.form.email.ph": "tuum@email.com", "contact.form.message.ph": "Epistula tua...",
    "contact.success.title": "Epistula Accepta", "contact.success.body": "Gratias, {name}. Intra duos ad tres dies negotii tibi respondebimus.",
    "contact.enquiry.course": "De Cursu Interrogatio", "contact.enquiry.enrol": "Inscriptio", "contact.enquiry.partner": "Societas Institutionalis",
    "contact.enquiry.media": "Media / Prensa", "contact.enquiry.other": "Aliud",
    "footer.copy": "© 2025 Gramma Institute", "whatsapp.label": "WhatsApp",
  },
  fr: {
    "nav.home": "Accueil", "nav.about": "À Propos", "nav.glossary": "Glossaire", "nav.contact": "Nous Contacter",
    "hero.tagline": "Gramma Institute", "hero.headline1": "Lisez le Texte.", "hero.headline2": "Pas la Traduction.",
    "hero.subtitle": "Grec Biblique, Hébreu Biblique, Latin, Anglais, Portugais et Linguistique Descriptive — enseignés avec la rigueur qu'ils méritent, pour ceux qui ne se contentent pas d'une connaissance de seconde main.",
    "hero.explore": "EXPLORER LES COURS", "hero.touch": "NOUS CONTACTER", "hero.scroll": "DÉFILER",
    "courses.label": "Nos Langues", "courses.title1": "Six Langues.", "courses.title2": "Un Seul But.",
    "courses.body": "Le canon de la civilisation occidentale — théologique, philosophique et littéraire — a été écrit dans ces langues. Accédez-y directement.",
    "courses.learn": "En Savoir Plus",
    "why.label": "L'Argument pour les Sources Primaires", "why.title": "Pourquoi la Langue Originale",
    "why.1.title": "Précision Au-Delà de la Traduction", "why.1.body": "Toute traduction est une interprétation. Les traducteurs font des milliers de choix — en vocabulaire, syntaxe et nuance — que vous ne voyez jamais. Les langues originales éliminent entièrement cette couche.",
    "why.2.title": "Accès à l'Intention de l'Auteur", "why.2.body": "Les mots portent un poids propre à leur époque. Le grec de Paul, l'hébreu de Moïse, le latin d'Augustin — chacun porte un sens qu'aucun mot français ne peut pleinement capturer.",
    "why.3.title": "Discipline Intellectuelle", "why.3.body": "Apprendre des langues anciennes remodèle votre façon de penser. La grammaire exige de la précision. Le vocabulaire exige de l'attention. Le résultat est un esprit formé à l'exactitude.",
    "why.4.title": "Une Tradition Vivante", "why.4.body": "Vous rejoignez une chaîne de savants qui s'étend sur des siècles — moines, réformateurs, théologiens — qui croyaient que ces langues valaient l'effort.",
    "why.quote": '"Le texte original est le seul texte."',
    "cta.label": "Commencez Votre Étude", "cta.title1": "Le Texte Attend.", "cta.title2": "Êtes-Vous Prêt?",
    "cta.body": "Contactez-nous pour plus d'informations sur nos cours, nos horaires et l'inscription. Nous répondons personnellement à chaque demande.",
    "cta.button": "NOUS CONTACTER",
    "about.hero.label": "Gramma Institute", "about.hero.title1": "À Propos de", "about.hero.title2": "l'Institut",
    "about.mission.label": "Notre Mission", "about.mission.text": "Équiper des étudiants sérieux d'un accès direct et sans intermédiaire aux textes qui ont façonné la civilisation occidentale et la pensée chrétienne.",
    "about.mission.p1": "Le Gramma Institute a été fondé sur une conviction : que les textes les plus importants de l'histoire méritent d'être lus dans leurs langues originales. La traduction est une interprétation. Et toute interprétation, aussi fidèle soit-elle, introduit une distance entre le lecteur et le texte.",
    "about.mission.p2": "Nous réduisons cette distance. Par un enseignement rigoureux du Grec Biblique, de l'Hébreu Biblique, du Latin, de l'Anglais, du Portugais et de la Linguistique Descriptive.",
    "about.mission.p3": "Nos étudiants sont des pasteurs, des théologiens, des séminaristes, des universitaires et des chercheurs indépendants qui ne se satisfont pas d'une connaissance de seconde main.",
    "about.mission.p4": "Les langues que nous enseignons ne sont pas de simples matières académiques. Ce sont des fenêtres vivantes sur la Parole de Dieu et l'héritage intellectuel de l'Église.",
    "about.pillars.label": "Nos Principes", "about.pillars.title": "Ce Que Nous Défendons",
    "about.pillars.1.title": "Rigueur Sans Compromis", "about.pillars.1.body": "Nous n'enseignons pas des grammaires simplifiées ou des méthodes raccourcies. Nous enseignons les langues telles qu'elles ont été écrites — avec une morphologie, une syntaxe et une précision philologique complètes.",
    "about.pillars.2.title": "Apprentissage Centré sur le Texte", "about.pillars.2.body": "Chaque leçon conduit vers le texte primaire. La grammaire et le vocabulaire sont des outils. L'objectif est toujours le même : ouvrir le texte et le lire soi-même.",
    "about.pillars.3.title": "Sérieux Théologique", "about.pillars.3.body": "Ce ne sont pas simplement des langues classiques. Ce sont les langues de l'Écriture et de deux millénaires de pensée chrétienne.",
    "about.pillars.4.title": "Tradition Savante", "about.pillars.4.body": "Nos méthodes s'inscrivent dans une tradition d'enseignement des langues allant des grammairiens de la Réforme aux grandes universités d'Europe.",
    "about.cta.label": "Commencez", "about.cta.title": "Prêt à Lire le Texte?", "about.cta.body": "Choisissez votre langue et commencez. Tout grand savant a commencé là où vous êtes maintenant.",
    "about.cta.courses": "Voir les Cours", "about.cta.touch": "Nous Contacter",
    "glossary.hero.label": "Gramma Institute", "glossary.hero.title1": "Termes Clés en", "glossary.hero.title2": "Trois Langues",
    "glossary.hero.subtitle": "Un glossaire sélectionné de termes théologiquement et philologiquement significatifs — avec leur script original, translittération et notes savantes.",
    "glossary.tab.all": "Toutes les Langues", "glossary.tab.greek": "Grec", "glossary.tab.hebrew": "Hébreu", "glossary.tab.latin": "Latin",
    "glossary.search": "Rechercher des termes...", "glossary.empty": "Aucun terme trouvé pour",
    "contact.hero.label": "Gramma Institute", "contact.hero.title1": "Nous", "contact.hero.title2": "Contacter",
    "contact.hero.subtitle": "Que vous vous renseigniez sur un cours, envisagiez une inscription ou ayez une question — nous accueillons votre message.",
    "contact.info.label": "Correspondance", "contact.info.body": "Nous répondons à toutes les demandes dans un délai de deux à trois jours ouvrables.",
    "contact.email.label": "Email", "contact.response.label": "Délai de Réponse", "contact.response.value": "2–3 jours ouvrables",
    "contact.courses.label": "Cours", "contact.form.name": "Nom Complet *", "contact.form.email": "Adresse Email *",
    "contact.form.type": "Nature de la Demande", "contact.form.message": "Message *", "contact.form.send": "Envoyer le Message", "contact.form.sending": "Envoi en cours...",
    "contact.form.name.ph": "Votre nom", "contact.form.email.ph": "votre@email.com", "contact.form.message.ph": "Votre message...",
    "contact.success.title": "Message Reçu", "contact.success.body": "Merci, {name}. Nous vous contacterons dans un délai de deux à trois jours ouvrables.",
    "contact.enquiry.course": "Renseignement sur un Cours", "contact.enquiry.enrol": "Inscription", "contact.enquiry.partner": "Partenariat Institutionnel",
    "contact.enquiry.media": "Médias / Presse", "contact.enquiry.other": "Autre",
    "footer.copy": "© 2026 Gramma Institute Of Linguistics", "whatsapp.label": "WhatsApp",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const currentLangMeta = LANGUAGES.find((l) => l.code === lang)!;
  const dir = currentLangMeta.dir;

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
